name: CI Docker compose

#hml quando faz push ou merge na main e prd quando gera release
on:
  # push:
  #   branches: ["main"]
  release:
    types: [created]

jobs:

  cria-imagens-e-deploy-prd:
    name: Cria imagens e faz deploy PRD
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout do repo git
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: fabideia/quicktag:latest

      #aplica modificacoes
      - name: Cria SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/fabideia.pem
          echo "${{ secrets.DO_SSH_PRIVATE_KEY_FABIDEIA }}" > ~/.ssh/fabideia.pem
          ssh-keyscan -p 32780 -H 165.227.109.89 >> ~/.ssh/known_hosts

          cat >>~/.ssh/config <<END
          Host fabideia
            HostName 165.227.109.89
            IdentityFile ~/.ssh/fabideia.pem
            Port 32780
            User ubuntu
          
          END
          cat ~/.ssh/config

      - name: Copia docker-compose
        run: |
          scp iac/docker-compose-prd.yaml fabideia:/home/ubuntu/docker-quicktag/docker-compose.yaml       

      - name: Restarta containers
        run: |
          ssh fabideia 'cd docker-quicktag && docker compose pull && docker compose down && docker compose up -d  && docker system prune -af'

